# Generated by Django 5.0.7 on 2024-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='Nqnt9alwPxSKDl3W43r5', max_length=200, null=True),
        ),
    ]
