# Generated by Django 5.0.4 on 2024-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='4FPmWfyKOyL60ln4RIn5', max_length=200, null=True),
        ),
    ]
