# Generated by Django 5.0.4 on 2024-05-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_full_name_remove_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='80uLsUizhpJis1wp0lfE', max_length=200, null=True),
        ),
    ]
