# Generated by Django 5.0.4 on 2024-05-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='fGQxRQhx0zIzIDcOcBYt', max_length=200, null=True),
        ),
    ]
