# Generated by Django 5.0.3 on 2024-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='oQlNvyQ6muAxnTYBE4W9', max_length=200, null=True),
        ),
    ]
