# Generated by Django 5.0.3 on 2024-06-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='eudSFgHqgeuOQRwWkBXJ', max_length=200, null=True),
        ),
    ]
