# Generated by Django 5.0.3 on 2024-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='SYhOhiWwlKGqeP6XUIMx', max_length=200, null=True),
        ),
    ]
