# Generated by Django 5.0.3 on 2024-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='TjlhHZt5dIoSOE4VzK35', max_length=200, null=True),
        ),
    ]
