# Generated by Django 5.0.3 on 2024-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='HimUtYTRsdrk9NgRZpkX', max_length=200, null=True),
        ),
    ]
