# Generated by Django 5.0.3 on 2024-07-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='xdRiSiX6HCwnl70fmKRJ', max_length=200, null=True),
        ),
    ]
