# Generated by Django 5.0.3 on 2024-07-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='syL2OD1xobsUwAatOV6L', max_length=200, null=True),
        ),
    ]
