# Generated by Django 5.0.3 on 2024-07-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='ml5s7zpAB1sNBeJ0GT9b', max_length=200, null=True),
        ),
    ]
