# Generated by Django 5.0.3 on 2024-07-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='RCS2KhGOsl4hhB4h3ALG', max_length=200, null=True),
        ),
    ]
