# Generated by Django 5.0.7 on 2024-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='Tt8fbTurixgYHE1DvF9d', max_length=200, null=True),
        ),
    ]
