# Generated by Django 5.0.7 on 2024-07-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, default='Kd66x2y2atP0HaRnL7Uc', max_length=200, null=True),
        ),
    ]
