# Generated by Django 5.0.3 on 2024-07-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, default='gnivgTH3Y6', max_length=500, null=True),
        ),
    ]
