# Generated by Django 5.0.3 on 2024-07-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_booking_code'),
        ('hotel', '0010_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, default='cu7BFunCCq', max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.roomtype'),
        ),
    ]
