# Generated by Django 5.0.9 on 2024-10-02 07:30

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='company/')),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, default='default@default.com', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, default='01099999', max_length=150)),
                ('facebook', models.URLField(blank=True, max_length=500)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'MainSettings',
            },
        ),
    ]
