# Generated by Django 5.0.9 on 2024-10-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
