# Generated by Django 5.0.7 on 2024-07-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='company/')),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, default='default@default.com', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, default='01099999', max_length=150, null=True)),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'MainSettings',
            },
        ),
    ]
