# Generated by Django 5.0.9 on 2024-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Proccing', 'Proccing'), ('Paid', 'Paid'), ('Failed', 'Failed')], max_length=10),
        ),
    ]
