# Generated by Django 5.0.7 on 2024-09-09 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, choices=[('bed', 'Bed'), ('bath', 'Bath'), ('wifi', 'WiFi'), ('tv', 'TV'), ('fan', 'Fan'), ('user-cog', 'Laundry'), ('utensils', 'Dinner')], max_length=100, null=True)),
                ('feature', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('img', models.ImageField(upload_to='hotel/')),
                ('subtitle', models.TextField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=500, null=True)),
                ('tag', models.CharField(blank=True, choices=[('sale', 'Sale'), ('new', 'New'), ('featured', 'Featured'), ('cheap', 'Cheap'), ('luxury', 'Luxury'), ('popular', 'Popular')], default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hotel', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ManyToManyField(to='hotel.hotelfeatures')),
            ],
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='hotel gallery/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_gallery', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('rate', models.CharField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_review', to='hotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('price_start', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_end', models.DecimalField(decimal_places=2, max_digits=7)),
                ('beds_num', models.PositiveIntegerField()),
                ('room_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room_type', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.PositiveIntegerField()),
                ('view', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room', to='hotel.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='hotel.roomtype')),
            ],
        ),
    ]
