# Generated by Django 5.0.3 on 2024-06-22 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='defaul_name', max_length=500, null=True)),
                ('img', models.ImageField(upload_to='hotel/')),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('phone', models.CharField(blank=True, default='defaul_name', max_length=500, null=True)),
                ('address', models.CharField(blank=True, default='defaul_name', max_length=500, null=True)),
                ('email', models.EmailField(blank=True, default='defaul_name', max_length=500, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('tag', models.CharField(blank=True, choices=[('sale', 'sale'), ('new', 'new'), ('featured', 'featured'), ('cheap', 'cheap'), ('luxury', 'luxury'), ('popular', 'popular')], default='defaul_name', max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hotel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, choices=[('bed', 'bed'), ('bath', 'bath'), ('wifi', 'wifi'), ('tv', 'tv'), ('fan', 'fan'), ('user-cog', 'Laundry'), ('utensils', 'Dinner')], max_length=100, null=True)),
                ('feature', models.CharField(blank=True, default='defaul_name', max_length=500, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_features', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='hotel gallery/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_gallery', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('rate', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_review', to='hotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='defaul_name', max_length=500, null=True)),
                ('price_start', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_end', models.DecimalField(decimal_places=2, max_digits=7)),
                ('img', models.ImageField(upload_to='room type/')),
                ('beds_num', models.PositiveIntegerField()),
                ('room_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room_type', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.PositiveIntegerField()),
                ('view', models.CharField(blank=True, default='defaul_view', max_length=500, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room', to='hotel.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='hotel.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('cach', 'cach'), ('visa', 'visa'), ('strip', 'strip'), ('paypal', 'paypal')], max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=900, null=True)),
                ('before_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('money_saved', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('check_in_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('check_out_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('num_adults', models.PositiveIntegerField(blank=True, null=True)),
                ('num_children', models.PositiveIntegerField(blank=True, null=True)),
                ('check_in', models.BooleanField(default=False)),
                ('check_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('booking_code', models.CharField(blank=True, default='mAziDxv3dg', max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_user', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booked', to='hotel.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_room', to='hotel.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_room_type', to='hotel.roomtype')),
            ],
        ),
    ]
