# Generated by Django 5.0.3 on 2024-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, default='AcZncJsqfW', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, default='defaul_address', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, default='defaul_email', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, default='defaul_phone', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
