# Generated by Django 5.0.3 on 2024-06-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_booking_booking_code_alter_hotel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='subtitle',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, default='J5mUK5q2xY', max_length=500, null=True),
        ),
    ]
