# Generated by Django 5.0.7 on 2024-09-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_created_at_hotel_created_hotel_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created']},
        ),
    ]
