# Generated by Django 5.0.3 on 2024-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_subtitle_alter_booking_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, default='HMxjMwV25H', max_length=500, null=True),
        ),
    ]
