# Generated by Django 5.0.3 on 2024-06-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_min_price_alter_booking_booking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='img',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, default='4SyoFlZCVp', max_length=500, null=True),
        ),
    ]
