# Generated by Django 5.0.3 on 2024-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_booking_booking_code_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, default='D92ijJZlYd', max_length=500, null=True),
        ),
    ]
