# Generated by Django 5.0.9 on 2024-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/'),
        ),
    ]
